### ISSUE TITLE
Playground Run result does not show on Windows systems

### ISSUE THREAD

**Issue by tonydearaujo** [orta/typescript-play#10]
When displaying an example to the HTML body, such as when using the classes code example, the result is displayed out of of range and therefore, not seen.
I have tested  it on two different Windows computers and using all popular browsers.
If you look at the DOM, it’s there, it’s being inserted, but it’s outside the page visible area.
This is a major issue for Windows users.
Please help.

**Comment by orta** [comment]
Run still runs your code - we should change those demos, most people I talked to didn't want the behavior of the code running in a new tab. I'm open to a PR which brings that back, for now I'll close this issue and open one on the website https://github.com/microsoft/TypeScript-Website/issues/11
