### ISSUE TITLE
Old playground generated AMD modules

### ISSUE THREAD

**Issue by mihailik** [orta/typescript-play#3]
In old playground, if your code was a module (had import or export), it would generate AMD output, with `define(..., function() { ... })` wrappers etc.

The new playground seems to produce either commonjs or ES* modules (assuming determined by `target` option?) — which limits usefulness in some experimentations.

**Comment by orta** [comment]
Open to PRs adding support for the different module types, I've made an issue on the TypeScript website for it https://github.com/microsoft/TypeScript-Website/issues/6
