### ISSUE TITLE
Allow `tsconfig.json` settings in raw form

### ISSUE THREAD

**Issue by mihailik** [orta/typescript-play#4]
Options drop-down is sort of hard-coded, and limited (see <a href=""></a> for example).

Is it possible to allow parameters in raw tsconfig JSON please?

Especially useful for experimenting, and trying error cases in full compiler then copy-pasting in playground.

![image](https://user-images.githubusercontent.com/4041967/60288422-0b509b00-990c-11e9-9c39-073d5e898c03.png)

**Comment by orta** [comment]
Yeah, this seems reasonable - this is almost like a wizard and there should be an "expert" mode 👍 

Moved to the website https://github.com/microsoft/TypeScript-Website/issues/21
