### ISSUE TITLE
The playground fills your history tab

### ISSUE THREAD

**Issue by tjcrowder** [orta/typescript-play#6]
Thank you for this huge improvement on the old playground. (Which was already pretty good. This one's just...better!)

Having the code in the URL is great when you're ready for that, but doing it on every change (or so) fills up your history with fairly useless entries:

![typescript-playground-history](https://user-images.githubusercontent.com/27634/60506767-82947f00-9cbe-11e9-9c07-8053ab0d889f.png)

I suggest either:

1. Going back to the old playground's behavior where it only updates the address bar when you specifically ask it to, or better yet:
2. Having a "Copy shareable link" (or whatever) button that copies the link to the clipboard (and perhaps also updates the address bar). The current Ctrl+Shift+S keyboard shortcut could be mapped to this button.

**Comment by tjcrowder** [comment]
(Edited to highlight interaction with current Ctrl+Shift+S shortcut)

**Comment by orta** [comment]
This is a bug for sure, it shouldn't be doing that. I'll see if I can just fix this rather than moving it over to the typescript website.

**Comment by orta** [comment]
Ergh, when you use the browser API correctly it will correctly keep the back/forward buttons but won't do that for your history.

**Comment by orta** [comment]
Moved to the site: https://github.com/microsoft/TypeScript-Website/issues/8
