### ISSUE TITLE
Playground eats Ctrl+Shift+I (the shortcut to open devtools)

### ISSUE THREAD

**Issue by tjcrowder** [orta/typescript-play#7]
Love the new playground!

Unfortunately, if the playground editor has focus, trying to use Ctrl+Shift+I to open devtools doesn't work anymore. (Tried in Chrome and Firefox.) It doesn't seem to do anything at all.

Would be great if it wouldn't prevent Ctrl+Shift+I.

I can take a crack at it if you'd like, but not for a couple of weeks. :-(

**Workaround 1**: Use the menu (obviously). :-)

**Workaround 2**: On Chrome, you can use Ctrl+Shift+J, which still works. (You can on Firefox too, but it opens a new window rather than a docked one.)

**Comment by orta** [comment]
Thanks - I've moved it to. https://github.com/microsoft/TypeScript-Website/issues/10 - this feels like a bug to me yep!
