### ISSUE TITLE
Can't specify lib option

### ISSUE THREAD

**Issue by tjcrowder** [orta/typescript-play#8]
I was trying to help someone with a problem using `Object.entries` but the playground didn't think it existed. The options panel is great, but doesn't offer a way to specify the `lib` option. This is a fairly troublesome issue when trying to help people with their modern, up-to-date code.

Perhaps a short-term easy fix would be to default to the latest libs?

Eventually, being able to specify libs (or even a full `tsconfig.json` as suggested in #4) would probably be best.

**Comment by orta** [comment]
Yeah, this makes sense, I've re-created this issue over on the typescript website: https://github.com/microsoft/TypeScript-Website/issues/7
